name: Build next.js docker container
run-name: build next.js docker container
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      # - name: setup node v20
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: install next.js
      #   run: npm install next@latest react@latest react-dom@latest
      # - name: install deps
      #   run: cd site; npm install
      - name: build docker container
        run: cd site; docker build -t next-site-demo .
      - run: echo "Job's status is ${{ job.status }}."
  # build-sec-fix:
  #   runs-on: self-hosted
  #   steps:
  #     # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "branch name is ${{ github.ref }}"
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: setup node v20
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: install next.js
  #       run: npm install next@latest react@latest react-dom@latest
  #     - name: install deps
  #       run: cd site-sec-fix; npm install
  #     - name: build site
  #       run: cd site-sec-fix; npm run build
  #     - run: echo "Job's status is ${{ job.status }}."
  