name: Build next.js docker container
run-name: build next.js docker container
on: 
  push:
    branches: ['dev-static']

env:
  SITE: site-static
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-static:
    runs-on: self-hosted
    steps:
      - run: echo "branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install next.js
        run: cd ${{ env.SITE }}; npm install next@latest react@latest react-dom@latest
      - name: install deps
        run: cd ${{ env.SITE }}; npm install
      - name: build site
        run: cd ${{ env.SITE }}; npm run build
      - run: echo "Job's status is ${{ job.status }}."
