name: Build next.js docker container
run-name: build next.js docker container
on: 
  push:
    branches: ['dev-static']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-static:
    runs-on: self-hosted
    steps:
      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install next.js
        run: cd site; npm install next@latest react@latest react-dom@latest
      - name: install deps
        run: cd site; npm install

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
      # - name: build docker container
      #   run: cd site; docker build -t ${{ env.IMAGE_NAME }} .
      - run: echo "Job's status is ${{ job.status }}."
  # build-sec-fix:
  #   runs-on: self-hosted
  #   steps:
  #     # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "branch name is ${{ github.ref }}"
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: setup node v20
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: install next.js
  #       run: npm install next@latest react@latest react-dom@latest
  #     - name: install deps
  #       run: cd site-sec-fix; npm install
  #     - name: build site
  #       run: cd site-sec-fix; npm run build
  #     - run: echo "Job's status is ${{ job.status }}."
