name: Build next.js static website
run-name: build next.js static website
on: 
  push:
    branches: ['dev-static']

env:
  S3: next-static.deploy.ninja
  SITE: site-static
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-static:
    runs-on: self-hosted
    steps:
      - run: echo "branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install next.js
        run: cd ${{ env.SITE }}; npm install next@latest react@latest react-dom@latest
      - name: install deps
        run: cd ${{ env.SITE }}; npm install
      - name: build site
        run: cd ${{ env.SITE }}; npm run build
      - name: cp output to S3
        run: cd ${{ env.SITE }}; aws s3 cp out/ s3://${{ env.S3 }}/ --recursive
      - run: echo "Job's status is ${{ job.status }}."
